config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :bookmarks, except: [:index]
  end

  devise_for :users

  get 'about' => 'welcome#about'

  root 'welcome#index'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many  :bookmarks

  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :topics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def show
   @bookmark = Bookmark.find(params[:id])
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new
    @bookmark.url = params[:bookmark][:url]
    @bookmark.topic = Topic.find(params[:topic_id])

    if @bookmark.save
      flash[:notice] = "Bookmark was created!"
      redirect_to topics_path
    else
      flash.now[:alert] = "Failed creating bookmark, please try again."
      render :new
    end
  end

  def edit
   @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])

    @bookmark.assign_attributes(bookmark_params)

    if @bookmark.save
      flash[:notice] = "Bookmark is updated!"
      redirect_to [@bookmark.topic, @bookmark]
    else
      flash.now[:alert] = "Someting went wrong, try again."
      render :edit
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])

    if @bookmark.destroy
      flash[:notice] = "Bookmark have been destroyed!"
      redirect_to @bookmark.topic
    else
      flash[:alert] = "Couldn't delete the bookmark, try again"
      redirect_to [@bookmark.topic, @bookmark]
    end
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:url)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
    @bookmarks = Bookmark.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new
    @topic.title = params[:topic][:title]
    @topic.user = current_user

    if @topic.save
      redirect_to topics_path, notice: "Topic was created!"
    else
      flash.now[:alert] = "Couldn't create topic, try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])

    @topic.assign_attributes(topic_params)

    if @topic.save
      flash[:notice] = "Topic is updated"
      redirect_to @topic
    else
      flash[:alert] = "Someting went wrong, try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
      flash[:notice] = "\"#{@topic.title}\" was deleted successfully."
      redirect_to topics_path, notice: "Topic was deleted!"
    else
      flash[:alert] = "Topic couldn't be deleted, try again."
      render :show
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/edit.html.erb
<h1>Bookmarks#edit</h1>
<p>Find me in app/views/bookmarks/edit.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Bookmarks#new</h1>
<p>Find me in app/views/bookmarks/new.html.erb</p>

app/views/bookmarks/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="text-center">
      <h1><%= @bookmark.id %></h1>
      <%= link_to "Edit Topic", edit_topic_bookmark_path, class: 'btn btn-success' %>
      <%= link_to "Delete Topic", [@bookmark.topic, @bookmark], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this bookmark?' }  %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectBookmark</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <ul class="nav nav-tabs">
    <li><%= link_to "CompleteInSeven", root_path %></li>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Topics", topics_path %></li>

    <div class="pull-right user-info">
      <% if user_signed_in? %>
        <strong><%= link_to current_user.email, user_session_path(current_user) %></strong> |
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
        <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
  </ul>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">
  <div class="col-md-6">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter new name" %>
      </div>
      <%= f.submit "Update Topic", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="txtmid">All Topics</h1>
    <div class="text-center">
      <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
    </div>
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-12">
          <h4> <%= link_to topic.title, topic %></h4>

          <% topic.bookmarks.each do |bookmark| %>
             <div class="col-md-4">
               <div class="row">
                <%= link_to bookmark.id, [topic, bookmark]%>
               </div>
             </div>
          <% end %>

<!--
          # bookmarks belonging to said topic should be displayed here.
          @topic.bookmarks.each do |bookmark| %>
          #  bookmark picture or something</div>
          # Like button?
          #  end %>
          #  end %>
-->
      </div>
    </div>
      <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="col-md-6">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter Topic TItle" %>
      </div>
      <%= f.submit "Create", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="text-center">
      <h1><%= @topic.title %></h1>
      <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
      <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' }  %>
    </div>
  </div>
</div>

<br><br>

<div class="row">
  <% @topic.bookmarks.each do |bookmark| %>
    <div class="col-md-4">
      <div class="row">
        <%= bookmark.url %>
      </div>
    </div>
  <% end %>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>